<!-- This website is made using the Simpl framework. You can read more about Simpl here: https://www.github.com/IJuanTM/Simpl -->
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Page Title -->
  <title>Tic Tac Toe</title>

  <!-- Favicons -->
  <link rel="apple-touch-icon" sizes="180x180" href="<?= PageController::url(FAVICON . 'apple-touch-icon.png') ?>">
  <link rel="icon" type="image/png" sizes="32x32" href="<?= PageController::url(FAVICON . 'favicon-32x32.png') ?>">
  <link rel="icon" type="image/png" sizes="16x16" href="<?= PageController::url(FAVICON . 'favicon-16x16.png') ?>">
  <link rel="manifest" href="<?= PageController::url(FAVICON . 'site.webmanifest') ?>">
  <link rel="mask-icon" href="<?= PageController::url(FAVICON . 'safari-pinned-tab.svg') ?>" color="#0265DD">

  <!-- Meta and CSS -->
  <?php
  require_once META;
  require_once CSS;
  ?>
</head>
<body>
<!--No script-->
<noscript>To use this website to it's fullest potential, please enable JavaScript!</noscript>

<!-- Content -->
<main class="content center">
