<!-- Set charset -->
<meta charset="UTF-8">

<!-- Set viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Copyright and author -->
<meta name="copyright" content="&copy; Iwan van der Wal"/>
<meta name="author" lang="en" content="Iwan van der Wal"/>

<!-- Description and keywords -->
<meta name="description" content="Simpl is an easy-to-use HTML, PHP, CSS, Sass and JavaScript framework!">
<meta name="keywords" content="Simpl, HTML, PHP, CSS, SCSS, Sass, JavaScript, Framework, MVC">

<!-- IE support -->
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9">

<!-- Theme color -->
<meta name="msapplication-TileColor" content="#FFFFFF">
<meta name="theme-color" content="#FFFFFF">
