<section class="home">
  <div class="row info">
    <div class="col f-0">
      <section class="card">
        <div class="row">
          <div class="col reset center">
            <span class="material-icons-round" title="Clear scoreboard.">delete_outline</span>
          </div>
        </div>
      </section>
    </div>
    <div class="col">
      <section class="card">
        <div class="row">
          <div class="col">
            <div class="row scores">
              <div class="col f-0">
                <div class="o"></div>
              </div>
              <div class="col score center-y">
                <span id="o-score"></span>
              </div>
            </div>
          </div>
          <div class="col center">
            <span class="message"></span>
          </div>
          <div class="col">
            <div class="row scores">
              <div class="col score center-y end-x">
                <span id="x-score"></span>
              </div>
              <div class="col f-0">
                <div class="x"></div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    <div class="col f-0">
      <section class="card">
        <div class="row">
          <div class="col restart center">
            <span class="material-icons-round" title="Start a new game.">replay</span>
          </div>
        </div>
      </section>
    </div>
  </div>
  <div class="row tic-tac-toe">
    <div class="col">
      <section class="card game">
        <div class="row">
          <div class="col">
            <section class="field">
              <div class="row">
                <div class="col" id="0"></div>
                <div class="col" id="1"></div>
                <div class="col" id="2"></div>
              </div>
              <div class="row">
                <div class="col" id="3"></div>
                <div class="col" id="4"></div>
                <div class="col" id="5"></div>
              </div>
              <div class="row">
                <div class="col" id="6"></div>
                <div class="col" id="7"></div>
                <div class="col" id="8"></div>
              </div>
              <div class="h-line"></div>
              <div class="v-line"></div>
              <div class="d-line-l"></div>
              <div class="d-line-r"></div>
            </section>
          </div>
        </div>
      </section>
    </div>
  </div>
  <div class="row info">
    <div class="col">
      <section class="card small">
        <div class="row">
          <div class="col credits center">
            <span>Made by: <a href="https://github.com/IJuanTM" target="_blank">IJuanTM</a></span>
          </div>
        </div>
      </section>
    </div>
  </div>
</section>
